spring:
  application:
    name: kafka-processor
  cloud:
    function:
      definition: consumeMessage
    stream:
      default-binder: kafka
      bindings:
        consumeMessage-in-0:
          destination: topicA
          content-type: application/json
          group: validate-group
          consumer:
            partitioned: true

        # Kafka output binding
        publishToKafka-out-0:
          destination: execution-response
          binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          consumeMessage-in-0:
            consumer:
              configuration:
                max.poll.records: 100
      instance-count: ${REPLICA_COUNT:3}
      instance-index: ${POD_INDEX:0}

server:
  port: ${SERVER_PORT:8081}

nats:
  completionInterval: ${NATS_CLEANUP_INTERVAL:PT30S}
  spring:
    server: nats://localhost:4222
